#!/usr/bin/env bash
# errno.sh [MUSL_DIR]: print errno.S, the agent's error messages, generated
# from musl's own table: src/errno/__strerror.h for the texts, and
# arch/generic/bits/errno.h for the numbers (x86-64 has no errno.h of its
# own). The table is indexed by errno as musl's strerror indexes it, so the
# agent words an error exactly as the Rust agent (std over musl) did. See
# errno.md.
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
if [ $# -ge 1 ]; then
    musl=$1
else
    . "$here/../../toolchain/env.sh"
    musl="$phi_build/toolchain/musl-1.2.5"
fi
table="$musl/src/errno/__strerror.h"
numbers="$musl/arch/generic/bits/errno.h"
[ -f "$table" ] && [ -f "$numbers" ] || { echo "errno.sh: musl sources not found in $musl (toolchain/fetch.sh)" >&2; exit 1; }

awk -v numbers="$numbers" '
BEGIN {
    # Names to numbers, aliases (EWOULDBLOCK EAGAIN) resolved afterwards.
    while ((getline line < numbers) > 0) {
        n = split(line, f, /[ \t]+/)
        if (f[1] == "#define" && n >= 3) def[f[2]] = f[3]
    }
    for (k in def) {
        v = def[k]
        while (v in def) v = def[v]
        num[k] = v
    }
    num["0"] = 0
    max = 0
}
/^E\(/ {
    s = $0
    sub(/^E\([ \t]*/, "", s)
    name = s; sub(/[ \t]*,.*/, "", name)
    text = s; sub(/^[^"]*"/, "", text); sub(/"\)[ \t]*$/, "", text)
    if (!(name in num)) { print "errno.sh: no number for " name > "/dev/stderr"; exit 1 }
    code = num[name] + 0
    # musl: a designated initializer, so a later entry for the same code wins.
    msg[code] = text
    order[++count] = code
    if (code > max) max = code
}
END {
    print "# errno.S: generated by errno.sh from musl 1.2.5 (src/errno/__strerror.h,"
    print "# arch/generic/bits/errno.h). Do not edit by hand; see errno.md."
    print "\t.include \"defs.inc\""
    print "\t.section .rodata"
    print "\t.globl errno_count, errno_index, errno_text"
    print "# Entries in errno_index: an errno at or past it reads as entry 0."
    print "errno_count:\n\t.quad " max + 1
    # Offsets into errno_text, one u16 per errno; codes without a message
    # point at entry 0 ("No error information"), as in musl.
    off = 0
    for (i = 1; i <= count; i++) {
        c = order[i]
        if (c in at) continue
        at[c] = off
        text_of[off] = msg[c]
        offs[++nofs] = off
        off += length(msg[c]) + 1
    }
    printf "errno_index:"
    for (c = 0; c <= max; c++) {
        o = (c in at) ? at[c] : 0
        printf "%s%d", (c % 16 == 0) ? "\n\t.short " : ", ", o
    }
    print ""
    print "errno_text:"
    for (i = 1; i <= nofs; i++) printf "\t.asciz \"%s\"\n", text_of[offs[i]]
}
' "$table"
