//! `knc-mvex-gen`: writes the project's hand-vectorised Knights Corner code
//! as assembly with `.byte`-encoded vector instructions, and the kernel's
//! vector state save/restore header. Everything comes from the encoder in
//! lib.rs, so a change there regenerates all three:
//!
//! ```text
//! knc-mvex-gen probe         > card/examples/vpu_probe.S
//! knc-mvex-gen mandel        > card/examples/mandel_vpu.S
//! knc-mvex-gen kernel-header > arch/x86/include/asm/knc_vpu.h   (in the kernel tree)
//! ```
//!
//! Scalar instructions are written as ordinary AT&T mnemonics; only the
//! vector and mask instructions are byte sequences. See main.md.

use knc_mvex::*;
use std::env;
use std::fmt::Write;

const RDI: Mem = Mem { base: Gpr::Rdi, disp: 0 };

fn at(base: Gpr, disp: i32) -> Src {
    Src::Mem(Mem::new(base, disp))
}

fn mem(base: Gpr, disp: i32) -> Mem {
    Mem::new(base, disp)
}

fn z(n: u8) -> Src {
    Src::Reg(Zmm(n))
}

fn header(what: &str, doc: &str) -> String {
    format!(
        "# {what}: generated by knc-mvex-gen (host/crates/knc-mvex). Do not edit by hand;\n# see {doc}. Vector instructions are .byte sequences because no assembler in\n# the stack knows the Knights Corner MVEX encoding.\n\t.text\n"
    )
}

/// Load zmm0..31 and k0..k7 from the 64-byte aligned area in `rdi`
/// (32 x 64 bytes, then eight 16-bit masks at 2048).
fn set_body(out: &mut String) {
    for r in 0..32u8 {
        writeln!(out, "{}", vmovapd_load(Zmm(r), at(Gpr::Rdi, 64 * i32::from(r)), K(0)).gas()).unwrap();
    }
    for k in 0..8u8 {
        writeln!(out, "\tmovzwl {}(%rdi), %eax", 2048 + 2 * i32::from(k)).unwrap();
        writeln!(out, "{}", kmov_k_r32(K(k), Gpr::Rax).gas()).unwrap();
    }
}

fn get_body(out: &mut String) {
    for r in 0..32u8 {
        writeln!(out, "{}", vmovapd_store(mem(Gpr::Rdi, 64 * i32::from(r)), Zmm(r), K(0)).gas()).unwrap();
    }
    for k in 0..8u8 {
        writeln!(out, "{}", kmov_r32_k(Gpr::Rax, K(k)).gas()).unwrap();
        writeln!(out, "\tmovw %ax, {}(%rdi)", 2048 + 2 * i32::from(k)).unwrap();
    }
}

fn function(out: &mut String, name: &str, signature: &str) {
    writeln!(out, "\n\t.globl {name}\n\t.type {name}, @function\n# {signature}\n{name}:").unwrap();
}

fn end_function(out: &mut String, name: &str) {
    writeln!(out, "\tret\n\t.size {name}, .-{name}").unwrap();
}

fn probe() -> String {
    let mut s = header("vpu_probe.S", "vpu_probe.md");
    function(
        &mut s,
        "vpu_probe",
        "void vpu_probe(const double *in, double *out, unsigned *mask): rdi = in (a at 0, b at 64), rsi = out, rdx = mask",
    );
    let lines = [
        vmovapd_load(Zmm(0), at(Gpr::Rdi, 0), K(0)),
        vmovapd_load(Zmm(1), at(Gpr::Rdi, 64), K(0)),
        vaddpd(Zmm(2), Zmm(0), z(1), K(0)),
        vmovapd_store(mem(Gpr::Rsi, 0), Zmm(2), K(0)),
        vmulpd(Zmm(3), Zmm(0), z(1), K(0)),
        vmovapd_store(mem(Gpr::Rsi, 64), Zmm(3), K(0)),
        vmovapd_load(Zmm(4), z(0), K(0)),
        vfmadd213pd(Zmm(4), Zmm(1), z(0), K(0)),
        vmovapd_store(mem(Gpr::Rsi, 128), Zmm(4), K(0)),
        vsubpd(Zmm(5), Zmm(0), z(1), K(0)),
        vmovapd_store(mem(Gpr::Rsi, 192), Zmm(5), K(0)),
        vmovapd_load(Zmm(31), z(2), K(0)),
        vmovapd_store(mem(Gpr::Rsi, 256), Zmm(31), K(0)),
    ];
    for l in &lines {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    writeln!(s, "\tmovl $15, %eax").unwrap();
    writeln!(s, "{}", kmov_k_r32(K(3), Gpr::Rax).gas()).unwrap();
    for l in [
        vmovapd_load(Zmm(6), z(1), K(0)),
        vaddpd(Zmm(6), Zmm(0), z(0), K(3)),
        vmovapd_store(mem(Gpr::Rsi, 320), Zmm(6), K(0)),
        vcmppd(K(2), Zmm(0), z(1), Cmp::Lt, K(0)),
        kmov_r32_k(Gpr::Rax, K(2)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    writeln!(s, "\tmovl %eax, (%rdx)").unwrap();
    end_function(&mut s, "vpu_probe");

    function(
        &mut s,
        "vpu_set",
        "void vpu_set(const void *area): rdi = 64-byte aligned area, 32 x 64 bytes of zmm then 8 x u16 masks at 2048",
    );
    set_body(&mut s);
    end_function(&mut s, "vpu_set");
    function(&mut s, "vpu_get", "void vpu_get(void *area): the same layout, stored");
    get_body(&mut s);
    end_function(&mut s, "vpu_get");
    writeln!(s, "\n\t.section .note.GNU-stack,\"\",@progbits").unwrap();
    let _ = RDI;
    s
}

fn mandel() -> String {
    let mut s = header("mandel_vpu.S", "mandel_vpu.md");
    function(&mut s, "mandel8_vpu", "void mandel8_vpu(const double *c, double *out, int maxiter): rdi = c (cr at 0, ci at 64), rsi = out (iteration counts at 0, |z|^2 at 64), edx = maxiter");
    writeln!(s, "\tleaq mandel8_consts(%rip), %rcx").unwrap();
    // Registers: 0 cr, 1 ci, 2 zr, 3 zi, 4 zr2, 5 zi2, 6 n, 7 two, 8 four, 9 one, 10 |z|^2, 11 2*zr.
    for l in [
        vmovapd_load(Zmm(0), at(Gpr::Rdi, 0), K(0)),
        vmovapd_load(Zmm(1), at(Gpr::Rdi, 64), K(0)),
        vmovapd_load(Zmm(2), at(Gpr::Rcx, 192), K(0)),
        vmovapd_load(Zmm(3), at(Gpr::Rcx, 192), K(0)),
        vmovapd_load(Zmm(4), at(Gpr::Rcx, 192), K(0)),
        vmovapd_load(Zmm(5), at(Gpr::Rcx, 192), K(0)),
        vmovapd_load(Zmm(6), at(Gpr::Rcx, 192), K(0)),
        vmovapd_load(Zmm(7), at(Gpr::Rcx, 0), K(0)),
        vmovapd_load(Zmm(8), at(Gpr::Rcx, 64), K(0)),
        vmovapd_load(Zmm(9), at(Gpr::Rcx, 128), K(0)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    writeln!(s, "\tmovl $255, %eax").unwrap();
    writeln!(s, "{}", kmov_k_r32(K(1), Gpr::Rax).gas()).unwrap();
    writeln!(s, "\txorl %r8d, %r8d").unwrap();
    writeln!(s, "1:").unwrap();
    // k1 &= (zr2 + zi2 < 4); stop when no lane is active.
    for l in [
        vaddpd(Zmm(10), Zmm(4), z(5), K(0)),
        vcmppd(K(1), Zmm(10), z(8), Cmp::Lt, K(1)),
        kortest(K(1), K(1)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    writeln!(s, "\tjz 2f").unwrap();
    // Active lanes: zi = 2*zr*zi + ci; zr = zr2 - zi2 + cr; zr2 = zr*zr; zi2 = zi*zi; n += 1.
    for l in [
        vmulpd(Zmm(11), Zmm(2), z(7), K(1)),
        vfmadd213pd(Zmm(3), Zmm(11), z(1), K(1)),
        vsubpd(Zmm(2), Zmm(4), z(5), K(1)),
        vaddpd(Zmm(2), Zmm(2), z(0), K(1)),
        vmulpd(Zmm(4), Zmm(2), z(2), K(1)),
        vmulpd(Zmm(5), Zmm(3), z(3), K(1)),
        vaddpd(Zmm(6), Zmm(6), z(9), K(1)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    writeln!(s, "\tincl %r8d\n\tcmpl %edx, %r8d\n\tjl 1b").unwrap();
    writeln!(s, "2:").unwrap();
    for l in [
        vmovapd_store(mem(Gpr::Rsi, 0), Zmm(6), K(0)),
        vaddpd(Zmm(10), Zmm(4), z(5), K(0)),
        vmovapd_store(mem(Gpr::Rsi, 64), Zmm(10), K(0)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    end_function(&mut s, "mandel8_vpu");
    writeln!(s, "\n\t.section .rodata\n\t.balign 64\nmandel8_consts:").unwrap();
    for v in ["2.0", "4.0", "1.0", "0.0"] {
        let row: Vec<&str> = vec![v; 8];
        writeln!(s, "\t.double {}", row.join(", ")).unwrap();
    }
    writeln!(s, "\n\t.section .note.GNU-stack,\"\",@progbits").unwrap();
    s
}

fn kernel_header() -> String {
    let mut s = String::new();
    s.push_str("/* SPDX-License-Identifier: GPL-2.0 */\n");
    s.push_str("/*\n * Knights Corner vector unit state: 32 zmm registers of 64 bytes and 8\n");
    s.push_str(" * mask registers of 16 bits, kept after the FXSAVE image in the task's\n");
    s.push_str(" * fpstate. FXSAVE does not store the zmm registers and FXRSTOR clears\n");
    s.push_str(" * bits 0:127 of every one of them (ISA reference 327364-001, B.5 and\n");
    s.push_str(" * B.4), so the restore has to run after fxrstor.\n *\n");
    s.push_str(" * Generated by knc-mvex-gen kernel-header (host/crates/knc-mvex in the\n");
    s.push_str(" * project tree), whose tests pin the encodings to Intel's k1om kernel\n");
    s.push_str(" * macros. Vector instructions are byte sequences because the assembler\n");
    s.push_str(" * does not know the MVEX prefix.\n */\n");
    s.push_str("#ifndef _ASM_X86_KNC_VPU_H\n#define _ASM_X86_KNC_VPU_H\n\n");
    s.push_str("#define KNC_VPU_STATE_OFFSET\t512\t/* right after the FXSAVE image */\n");
    s.push_str("#define KNC_VPU_K_OFFSET\t2048\t/* the mask registers, after the zmm registers */\n");
    s.push_str("#define KNC_VPU_STATE_SIZE\t2112\t/* zmm and masks, rounded up to 64 bytes */\n");
    s.push_str("#define KNC_FPSTATE_SIZE\t(KNC_VPU_STATE_OFFSET + KNC_VPU_STATE_SIZE)\n\n");
    s.push_str("#ifndef __ASSEMBLY__\n\n");
    s.push_str("/* Store zmm0..31 and k0..k7 into a 64-byte aligned area of KNC_VPU_STATE_SIZE bytes. */\n");
    s.push_str("static inline void knc_vpu_save(void *area)\n{\n\tasm volatile(\n");
    for r in 0..32u8 {
        writeln!(s, "\t\t{}", vmovaps_store(mem(Gpr::Rax, 64 * i32::from(r)), Zmm(r)).c_string()).unwrap();
    }
    for k in 0..8u8 {
        writeln!(s, "\t\t{}", kmov_r32_k(Gpr::Rcx, K(k)).c_string()).unwrap();
        writeln!(s, "\t\t\"movw %%cx, {}(%%rax)\\n\\t\"", 2048 + 2 * i32::from(k)).unwrap();
    }
    s.push_str("\t\t: : \"a\" (area) : \"rcx\", \"memory\");\n}\n\n");
    s.push_str("/* Load them back; call after fxrstor, which zeroes the low 128 bits of each zmm. */\n");
    s.push_str("static inline void knc_vpu_restore(const void *area)\n{\n\tasm volatile(\n");
    for r in 0..32u8 {
        writeln!(s, "\t\t{}", vmovaps_load(Zmm(r), mem(Gpr::Rax, 64 * i32::from(r))).c_string()).unwrap();
    }
    for k in 0..8u8 {
        writeln!(s, "\t\t\"movzwl {}(%%rax), %%ecx\\n\\t\"", 2048 + 2 * i32::from(k)).unwrap();
        writeln!(s, "\t\t{}", kmov_k_r32(K(k), Gpr::Rcx).c_string()).unwrap();
    }
    s.push_str("\t\t: : \"a\" (area) : \"rcx\", \"memory\");\n}\n\n");
    s.push_str("#endif /* __ASSEMBLY__ */\n#endif /* _ASM_X86_KNC_VPU_H */\n");
    s
}

fn main() {
    let what = env::args().nth(1).unwrap_or_default();
    let text = match what.as_str() {
        "probe" => probe(),
        "mandel" => mandel(),
        "kernel-header" => kernel_header(),
        _ => {
            eprintln!("usage: knc-mvex-gen probe|mandel|kernel-header");
            std::process::exit(2);
        }
    };
    print!("{text}");
}
