//! `knc-mvex-gen`: writes the project's hand-vectorised Knights Corner code
//! as assembly with `.byte`-encoded vector instructions, and the kernel's
//! vector state save/restore header. Everything comes from the encoder in
//! lib.rs, so a change there regenerates every one of them:
//!
//! ```text
//! knc-mvex-gen probe         > card/examples/vpu_probe.S
//! knc-mvex-gen int-probe     > card/examples/vpu_int.S
//! knc-mvex-gen bitunpack     > card/examples/bitunpack.S
//! knc-mvex-gen codec         > the libknc kernels, every width, both directions
//! knc-mvex-gen fastlanes     > the FastLanes-layout unffor kernels, widths 0 to 32
//! knc-mvex-gen mandel        > card/examples/mandel_vpu.S
//! knc-mvex-gen kernel-header > arch/x86/include/asm/knc_vpu.h   (in the kernel tree)
//! knc-mvex-gen memcpy        > card/examples/vpu_memcpy.S
//! ```
//!
//! Scalar instructions are written as ordinary AT&T mnemonics; only the
//! vector and mask instructions are byte sequences. See main.md.

use knc_mvex::*;
use std::env;
use std::fmt::Write;

fn at(base: Gpr, disp: i32) -> Src {
    Src::Mem(Mem::new(base, disp))
}

fn mem(base: Gpr, disp: i32) -> Mem {
    Mem::new(base, disp)
}

fn z(n: u8) -> Src {
    Src::Reg(Zmm(n))
}

fn header(what: &str, doc: &str) -> String {
    format!(
        "# {what}: generated by knc-mvex-gen (host/crates/knc-mvex). Do not edit by hand;\n# see {doc}. Vector instructions are .byte sequences because no assembler in\n# the stack knows the Knights Corner MVEX encoding.\n\t.text\n"
    )
}

/// Load zmm0..31 and k0..k7 from the 64-byte aligned area in `rdi`
/// (32 x 64 bytes, then eight 16-bit masks at 2048).
fn set_body(out: &mut String) {
    for r in 0..32u8 {
        writeln!(out, "{}", vmovapd_load(Zmm(r), at(Gpr::Rdi, 64 * i32::from(r)), K(0)).gas()).unwrap();
    }
    for k in 0..8u8 {
        writeln!(out, "\tmovzwl {}(%rdi), %eax", 2048 + 2 * i32::from(k)).unwrap();
        writeln!(out, "{}", kmov_k_r32(K(k), Gpr::Rax).gas()).unwrap();
    }
}

fn get_body(out: &mut String) {
    for r in 0..32u8 {
        writeln!(out, "{}", vmovapd_store(mem(Gpr::Rdi, 64 * i32::from(r)), Zmm(r), K(0)).gas()).unwrap();
    }
    for k in 0..8u8 {
        writeln!(out, "{}", kmov_r32_k(Gpr::Rax, K(k)).gas()).unwrap();
        writeln!(out, "\tmovw %ax, {}(%rdi)", 2048 + 2 * i32::from(k)).unwrap();
    }
}

fn function(out: &mut String, name: &str, signature: &str) {
    writeln!(out, "\n\t.globl {name}\n\t.type {name}, @function\n# {signature}\n{name}:").unwrap();
}

fn end_function(out: &mut String, name: &str) {
    writeln!(out, "\tret\n\t.size {name}, .-{name}").unwrap();
}

/// `knc_memcpy64`: copy whole 64-byte blocks between 64-byte aligned
/// pointers, using the full width of the vector unit.
///
/// The card's scalar memcpy is not bandwidth-limited at the sizes that
/// matter; it is overhead-limited. Measured on 2026-09-20, musl's memcpy
/// needs about 206 cycles to move 64 bytes and 72 cycles to move 8, almost
/// all of it size dispatch and alignment branching on a core that cannot
/// predict a branch. One `vmovaps` pair moves 64 bytes in two instructions.
///
/// Unrolled by four because the core is in-order: four loads issue before
/// the first store needs its result, which is the only way to overlap
/// memory latency without an out-of-order window.
fn memcpy_kernel() -> String {
    let mut s = header("vpu_memcpy.S", "vpu_memcpy.md");
    function(
        &mut s,
        "knc_memcpy64",
        "void *knc_memcpy64(void *dst, const void *src, size_t blocks): rdi = dst (64-byte aligned), rsi = src (64-byte aligned), rdx = count of 64-byte blocks. Returns dst.",
    );
    writeln!(s, "\tmovq %rdi, %rax").unwrap(); // return value
    writeln!(s, "\tcmpq $4, %rdx").unwrap();
    writeln!(s, "\tjb 2f").unwrap();
    writeln!(s, "1:").unwrap();
    for (i, r) in [0u8, 1, 2, 3].iter().enumerate() {
        writeln!(s, "{}", vmovaps_load(Zmm(*r), mem(Gpr::Rsi, 64 * i as i32)).gas()).unwrap();
    }
    for (i, r) in [0u8, 1, 2, 3].iter().enumerate() {
        writeln!(s, "{}", vmovaps_store(mem(Gpr::Rdi, 64 * i as i32), Zmm(*r)).gas()).unwrap();
    }
    writeln!(s, "\taddq $256, %rsi").unwrap();
    writeln!(s, "\taddq $256, %rdi").unwrap();
    writeln!(s, "\tsubq $4, %rdx").unwrap();
    writeln!(s, "\tcmpq $4, %rdx").unwrap();
    writeln!(s, "\tjae 1b").unwrap();
    writeln!(s, "2:").unwrap();
    writeln!(s, "\ttestq %rdx, %rdx").unwrap();
    writeln!(s, "\tjz 4f").unwrap();
    writeln!(s, "3:").unwrap();
    writeln!(s, "{}", vmovaps_load(Zmm(0), mem(Gpr::Rsi, 0)).gas()).unwrap();
    writeln!(s, "{}", vmovaps_store(mem(Gpr::Rdi, 0), Zmm(0)).gas()).unwrap();
    writeln!(s, "\taddq $64, %rsi").unwrap();
    writeln!(s, "\taddq $64, %rdi").unwrap();
    writeln!(s, "\tdecq %rdx").unwrap();
    writeln!(s, "\tjnz 3b").unwrap();
    writeln!(s, "4:").unwrap();
    end_function(&mut s, "knc_memcpy64");
    writeln!(s, "\n\t.section .note.GNU-stack,\"\",@progbits").unwrap();
    s
}

/// What a decode kernel does with each value after it comes out of the
/// bit-packed stream.
///
/// These are the lightweight encodings FastLanes cascades, and they are why
/// bit-packing alone is only the bottom layer: real columnar data is not
/// small because its values are small, it is small because its values are
/// close together (FOR) or close to their neighbours (DELTA).
#[derive(Clone, Copy, PartialEq, Eq)]
enum Mode {
    /// The value is the value.
    Plain,
    /// Frame of reference: add a per-lane base. One independent `vpaddd`
    /// per value, so it costs a single instruction and nothing else.
    For,
    /// Delta: each value is the difference from the one before it in the
    /// same lane, so decoding is a running sum along positions. That is a
    /// dependent chain 64 deep and it cannot be pipelined away: the chain
    /// *is* the algorithm. It survives only because all sixteen lanes run
    /// their own chain at once and the bit-unpacking of the next group has
    /// no dependency on it.
    Delta,
}

impl Mode {
    fn suffix(self) -> &'static str {
        match self {
            Mode::Plain => "",
            Mode::For => "_for",
            Mode::Delta => "_delta",
        }
    }

    fn all() -> [Mode; 3] {
        [Mode::Plain, Mode::For, Mode::Delta]
    }
}

/// Values processed together by both kernels. Eight independent chains is
/// more than the vector unit's latency needs, and it leaves room inside 32
/// registers for the words and the mask.
const GROUP: usize = 8;
/// Word registers for the unpack kernel: `zmm0` upward. A group of eight
/// values never touches more than `ceil(8*32/32) + 1 = 9` words, at any bit
/// width, so ten is the bound with a register to spare.
const WORD_REGS: u8 = 10;

/// Where value `v` of a block of `bits`-bit values sits: which 32-bit word
/// of its lane it starts in, and how far up that word.
fn place(bits: u32, v: usize) -> (usize, u8) {
    let bitpos = bits as usize * v;
    (bitpos / 32, (bitpos % 32) as u8)
}

/// `knc_unpack_bN`: unpack 1024 values of N bits into 1024 int32, using the
/// vector unit.
///
/// The layout is the one that makes bit-packing vectorisable at all, and it
/// is the reason FastLanes exists (docs/research/compression-on-knc.md).
/// Value `i` of the block lives in lane `i % 16` at position `i / 16`, so
/// each of the 16 lanes carries its own independent 64-value bitstream and
/// all 16 streams sit at the same bit offset at the same time. Word `w` of
/// every lane is therefore one 64-byte vector at `packed + 64*w`, and a
/// single shift-and-mask pair extracts one value from all 16 lanes at once.
/// Nothing crosses a lane, which matters here because the card has no byte
/// shuffle and no cross-lane permute worth using.
///
/// Each value needs one of five fixed sequences, decided here rather than
/// at run time, because the bit offsets are compile-time constants:
///
/// | Case | Instructions |
/// | --- | --- |
/// | the value is the whole word (N = 32) | none, store the word |
/// | starts at a word boundary | `vpandd` |
/// | ends at a word boundary | `vpsrld` |
/// | inside one word | `vpsrld`, `vpandd` |
/// | straddles two words | `vpsrld`, `vpslld`, `vpord`, `vpandd` |
///
/// No branch, no variable shift, no cross-lane traffic.
///
/// **The emission is software-pipelined, and that is most of the
/// performance.** The core is in order and a vector result is not ready for
/// the next instruction for several cycles, so emitting one value's whole
/// chain before starting the next stalls on every instruction: the first
/// version of this kernel did exactly that and reached 1.07 values per
/// cycle, about 15 cycles for a four-instruction chain
/// (`docs/results/2026-09-20-bitunpack.md`). Instead `GROUP` values are
/// processed together and the emission goes phase by phase, all the first
/// shifts, then all the second shifts, then all the ors, then all the
/// masks, then all the stores, so consecutive instructions are always from
/// different values and never dependent.
///
/// The words a group needs are loaded at the top of the group. That costs
/// a few more loads than the theoretical minimum of `2N` for the block,
/// because groups overlap at word boundaries, but they hit L1 and it
/// removes the need to hold the whole block's words in registers.
fn unpack_kernel(out: &mut String, bits: u32, mode: Mode) {
    let temp = |p: usize, half: usize| Zmm(WORD_REGS + (2 * p + half) as u8);
    let maskreg = Zmm(30);
    // The frame of reference, and the running sum, each need one register
    // live across the whole kernel. Neither mode uses the other's.
    let base = Zmm(26);
    let acc = Zmm(27);
    let name = format!("knc_unpack{}_b{bits}", mode.suffix());

    let sig = match mode {
        Mode::Plain => format!("void {name}(int *out, const unsigned *packed): rdi = out (1024 int32, 64-byte aligned), rsi = packed ({} bytes, 64-byte aligned)", 64 * 2 * bits),
        Mode::For => format!("void {name}(int *out, const unsigned *packed, const int *base): rdi = out, rsi = packed ({} bytes), rdx = base (16 int32, one per lane); all 64-byte aligned", 64 * 2 * bits),
        Mode::Delta => format!("void {name}(int *out, const unsigned *packed, const int *base): rdi = out, rsi = packed ({} bytes), rdx = base (16 int32, the value before position 0 in each lane); all 64-byte aligned", 64 * 2 * bits),
    };
    function(out, &name, &sig);
    if mode == Mode::For {
        writeln!(out, "{}", vmovaps_load(base, mem(Gpr::Rdx, 0)).gas()).unwrap();
    }
    if mode == Mode::Delta {
        writeln!(out, "{}", vmovaps_load(acc, mem(Gpr::Rdx, 0)).gas()).unwrap();
    }
    if bits < 32 {
        writeln!(out, "\tleaq knc_mask_b{bits}(%rip), %rax").unwrap();
        writeln!(out, "{}", vmovaps_load(maskreg, mem(Gpr::Rax, 0)).gas()).unwrap();
    }

    for start in (0..64).step_by(GROUP) {
        let group: Vec<usize> = (start..start + GROUP).collect();
        let first_word = place(bits, group[0]).0;
        let last = *group.last().unwrap();
        let last_word = (bits as usize * last + bits as usize - 1) / 32;
        let n_words = last_word - first_word + 1;

        assert!(
            n_words <= WORD_REGS as usize,
            "a group of {GROUP} values of {bits} bits needs {n_words} words"
        );
        for w in 0..n_words {
            let off = 64 * (first_word + w) as i32;
            writeln!(out, "{}", vmovaps_load(Zmm(w as u8), mem(Gpr::Rsi, off)).gas()).unwrap();
        }
        let wreg = |w: usize| Zmm((w - first_word) as u8);
        // Where each value's finished result ends up: its own temporary,
        // except at N = 32 where the word register already holds it.
        let result = |p: usize, v: usize| {
            if bits == 32 {
                wreg(place(bits, v).0)
            } else {
                temp(p, 0)
            }
        };

        // The low part, for every value that is not already word-aligned.
        for (p, &v) in group.iter().enumerate() {
            let (w, s) = place(bits, v);
            if s != 0 {
                writeln!(out, "{}", vpsrld(temp(p, 0), Src::Reg(wreg(w)), s, K(0)).gas()).unwrap();
            }
        }
        // The high part of the values that straddle two words.
        for (p, &v) in group.iter().enumerate() {
            let (w, s) = place(bits, v);
            if u32::from(s) + bits > 32 {
                writeln!(out, "{}", vpslld(temp(p, 1), Src::Reg(wreg(w + 1)), 32 - s, K(0)).gas()).unwrap();
            }
        }
        for (p, &v) in group.iter().enumerate() {
            let (_, s) = place(bits, v);
            if u32::from(s) + bits > 32 {
                writeln!(out, "{}", vpord(temp(p, 0), temp(p, 0), Src::Reg(temp(p, 1)), K(0)).gas()).unwrap();
            }
        }
        // The mask, dead for a value that ends at the top of a word.
        for (p, &v) in group.iter().enumerate() {
            let (w, s) = place(bits, v);
            if u32::from(s) + bits != 32 {
                let src = if s == 0 { wreg(w) } else { temp(p, 0) };
                writeln!(out, "{}", vpandd(temp(p, 0), src, Src::Reg(maskreg), K(0)).gas()).unwrap();
            }
        }
        match mode {
            Mode::Plain => {
                for (p, &v) in group.iter().enumerate() {
                    writeln!(out, "{}", vmovaps_store(mem(Gpr::Rdi, 64 * v as i32), result(p, v)).gas()).unwrap();
                }
            }
            Mode::For => {
                // Eight independent adds, then eight independent stores.
                for (p, &v) in group.iter().enumerate() {
                    writeln!(out, "{}", vpaddd(temp(p, 0), base, Src::Reg(result(p, v)), K(0)).gas()).unwrap();
                }
                for (p, &v) in group.iter().enumerate() {
                    writeln!(out, "{}", vmovaps_store(mem(Gpr::Rdi, 64 * v as i32), temp(p, 0)).gas()).unwrap();
                }
            }
            Mode::Delta => {
                // The running sum, in position order. Each add waits on the
                // one before it; the stores do not, so they interleave and
                // only the adds are on the critical path.
                for (p, &v) in group.iter().enumerate() {
                    writeln!(out, "{}", vpaddd(acc, acc, Src::Reg(result(p, v)), K(0)).gas()).unwrap();
                    writeln!(out, "{}", vmovaps_store(mem(Gpr::Rdi, 64 * v as i32), acc).gas()).unwrap();
                }
            }
        }
    }
    end_function(out, &name);
}

/// The encode-side transforms, which are their own pass rather than being
/// folded into the packer.
///
/// Folding them in would mean subtracting inside every piece of every word,
/// and a value that straddles two words is read twice, so it would be
/// subtracted twice. A separate pass over 64 vectors costs one instruction
/// per sixteen values and cannot get that wrong. Decoding is the direction
/// that has to be fast, and there the transform *is* folded in.
fn transform_kernel(out: &mut String, mode: Mode) {
    let (base, tmp) = (Zmm(26), Zmm(27));
    let name = format!("knc_encode{}", mode.suffix());
    let sig = match mode {
        Mode::For => format!("void {name}(int *out, const int *values, const int *base): out[i] = values[i] - base[lane]; rdi = out, rsi = values, rdx = base (16 int32); all 64-byte aligned"),
        Mode::Delta => format!("void {name}(int *out, const int *values, const int *base): out[i] = values[i] - the value before it in the same lane; rdi = out, rsi = values, rdx = base (16 int32, the value before position 0); all 64-byte aligned"),
        Mode::Plain => unreachable!("the plain encode is a copy"),
    };

    function(out, &name, &sig);
    writeln!(out, "{}", vmovaps_load(base, mem(Gpr::Rdx, 0)).gas()).unwrap();
    for v in 0..64usize {
        let slot = mem(Gpr::Rsi, 64 * v as i32);

        writeln!(out, "{}", vmovaps_load(tmp, slot).gas()).unwrap();
        // For DELTA the subtrahend becomes this value for the next position,
        // so the two-register shuffle is the whole of the state.
        writeln!(out, "{}", vpsubd(Zmm(28), tmp, Src::Reg(base), K(0)).gas()).unwrap();
        writeln!(out, "{}", vmovaps_store(mem(Gpr::Rdi, 64 * v as i32), Zmm(28)).gas()).unwrap();
        if mode == Mode::Delta {
            writeln!(out, "{}", vmovapd_load(base, Src::Reg(tmp), K(0)).gas()).unwrap();
        }
    }
    end_function(out, &name);
}

/// One value's contribution to one packed word: which value vector to read,
/// and how to move its bits into place.
struct Piece {
    value: usize,
    left: bool,
    amount: u8,
}

/// `knc_pack_bN`: the inverse, 1024 int32 into 1024 packed values of N bits.
///
/// Where unpacking is driven by values, packing is driven by **words**, and
/// that is what makes it schedulable. Each packed word is an independent
/// `or` of the two to thirty-two pieces that land in it; no word depends on
/// another, so `PACK_WORDS` of them are built at once and their chains
/// interleave. Within one word the chain is split across two partial
/// accumulators, halving its depth for the narrow widths where a single
/// word swallows many values.
///
/// Each piece is a load, a mask and a shift. The mask is not optional here
/// the way it is in `unpack`: a value with rubbish above bit N would
/// corrupt its neighbours in the packed word rather than only itself, and
/// this library is called from languages that cannot promise otherwise. It
/// costs one instruction per value.
fn pack_kernel(out: &mut String, bits: u32) {
    /// Packed words built at once, giving that many independent or-chains.
    const PACK_WORDS: usize = 4;
    /// Partial accumulators per word, to halve the chain depth.
    const WAYS: usize = 2;

    let acc = |j: usize, way: usize| Zmm((WAYS * j + way) as u8);
    let tmp = |j: usize| Zmm((PACK_WORDS * WAYS + j) as u8);
    let maskreg = Zmm(30);
    let words = 2 * bits as usize;
    let name = format!("knc_pack_b{bits}");

    // Which pieces make up each packed word.
    let mut pieces: Vec<Vec<Piece>> = (0..words).map(|_| Vec::new()).collect();
    for v in 0..64 {
        let (w, s) = place(bits, v);
        pieces[w].push(Piece {
            value: v,
            left: true,
            amount: s,
        });
        if u32::from(s) + bits > 32 {
            pieces[w + 1].push(Piece {
                value: v,
                left: false,
                amount: 32 - s,
            });
        }
    }

    function(
        out,
        &name,
        &format!("void {name}(unsigned *packed, const int *values): rdi = packed ({} bytes, 64-byte aligned), rsi = values (1024 int32, 64-byte aligned)", 64 * words),
    );
    if bits < 32 {
        writeln!(out, "\tleaq knc_mask_b{bits}(%rip), %rax").unwrap();
        writeln!(out, "{}", vmovaps_load(maskreg, mem(Gpr::Rax, 0)).gas()).unwrap();
    }

    for base in (0..words).step_by(PACK_WORDS) {
        let group: Vec<usize> = (base..(base + PACK_WORDS).min(words)).collect();
        let steps = group.iter().map(|&w| pieces[w].len()).max().unwrap();

        for i in 0..steps {
            // The first two pieces of a word land straight in its two
            // accumulators, so no register move is ever needed.
            let dst = |j: usize| if i < WAYS { acc(j, i) } else { tmp(j) };

            for (j, &w) in group.iter().enumerate() {
                if let Some(p) = pieces[w].get(i) {
                    let off = 64 * p.value as i32;
                    writeln!(out, "{}", vmovaps_load(dst(j), mem(Gpr::Rsi, off)).gas()).unwrap();
                }
            }
            if bits < 32 {
                for (j, &w) in group.iter().enumerate() {
                    if pieces[w].len() > i {
                        writeln!(out, "{}", vpandd(dst(j), dst(j), Src::Reg(maskreg), K(0)).gas()).unwrap();
                    }
                }
            }
            for (j, &w) in group.iter().enumerate() {
                if let Some(p) = pieces[w].get(i) {
                    if p.amount == 0 {
                        continue;
                    }
                    let insn = if p.left {
                        vpslld(dst(j), Src::Reg(dst(j)), p.amount, K(0))
                    } else {
                        vpsrld(dst(j), Src::Reg(dst(j)), p.amount, K(0))
                    };
                    writeln!(out, "{}", insn.gas()).unwrap();
                }
            }
            if i >= WAYS {
                for (j, &w) in group.iter().enumerate() {
                    if pieces[w].len() > i {
                        let a = acc(j, i % WAYS);
                        writeln!(out, "{}", vpord(a, a, Src::Reg(tmp(j)), K(0)).gas()).unwrap();
                    }
                }
            }
        }
        for (j, &w) in group.iter().enumerate() {
            if pieces[w].len() > 1 {
                writeln!(out, "{}", vpord(acc(j, 0), acc(j, 0), Src::Reg(acc(j, 1)), K(0)).gas()).unwrap();
            }
        }
        for (j, &w) in group.iter().enumerate() {
            writeln!(out, "{}", vmovaps_store(mem(Gpr::Rdi, 64 * w as i32), acc(j, 0)).gas()).unwrap();
        }
    }
    end_function(out, &name);
}

/// The width-dispatching entry points, `knc_unpack` and `knc_pack`, as
/// tail calls through the tables below. Ordinary scalar assembly: no MVEX
/// is involved, so this is written as mnemonics rather than bytes.
///
/// An out-of-range width returns without touching memory. A wild indirect
/// jump would be the alternative, and this library is called from Python
/// and JavaScript where the width can come from data.
fn dispatch_thunks(out: &mut String) {
    // The three-argument entry points take the width in edx, which is where
    // the kernel wants its third argument, so the base pointer has to move
    // down from rcx. Everything else is the same tail call.
    for (what, base, sig) in [
        ("unpack", false, "void knc_unpack(int *out, const void *packed, unsigned bits)"),
        ("pack", false, "void knc_pack(void *packed, const int *values, unsigned bits)"),
        (
            "unpack_for",
            true,
            "void knc_unpack_for(int *out, const void *packed, unsigned bits, const int *base)",
        ),
        (
            "unpack_delta",
            true,
            "void knc_unpack_delta(int *out, const void *packed, unsigned bits, const int *base)",
        ),
    ] {
        function(out, &format!("knc_{what}"), sig);
        writeln!(out, "\tmovl %edx, %eax").unwrap(); // a width is 32 bits wide
        writeln!(out, "\tdecl %eax").unwrap(); // 1..32 becomes 0..31, and 0 wraps high
        writeln!(out, "\tcmpl $31, %eax").unwrap();
        writeln!(out, "\tja 1f").unwrap();
        if base {
            writeln!(out, "\tmovq %rcx, %rdx").unwrap();
        }
        writeln!(out, "\tleaq knc_{what}_table(%rip), %r9").unwrap();
        writeln!(out, "\tjmp *8(%r9,%rax,8)").unwrap();
        writeln!(out, "1:").unwrap();
        end_function(out, &format!("knc_{what}"));
    }
}

/// Function tables, so a caller can pick a width at run time without a
/// switch of its own. Index 0 is null: a zero-bit value carries no
/// information and there is no kernel for it.
fn dispatch_tables(out: &mut String, widths: &[u32]) {
    for what in ["unpack", "pack", "unpack_for", "unpack_delta"] {
        writeln!(out, "\n\t.section .rodata\n\t.balign 8").unwrap();
        writeln!(out, "\t.globl knc_{what}_table\n\t.type knc_{what}_table, @object").unwrap();
        writeln!(out, "knc_{what}_table:").unwrap();
        writeln!(out, "\t.quad 0").unwrap();
        for bits in widths {
            let sym = match what {
                "unpack_for" => format!("knc_unpack_for_b{bits}"),
                "unpack_delta" => format!("knc_unpack_delta_b{bits}"),
                _ => format!("knc_{what}_b{bits}"),
            };
            writeln!(out, "\t.quad {sym}").unwrap();
        }
        writeln!(out, "\t.size knc_{what}_table, .-knc_{what}_table").unwrap();
    }
}

/// The lane masks both kernels read, one 64-byte constant per width.
fn mask_constants(out: &mut String, widths: &[u32]) {
    writeln!(out, "\n\t.section .rodata\n\t.balign 64").unwrap();
    for &bits in widths {
        if bits == 32 {
            continue;
        }
        let m = 0xFFFF_FFFFu32 >> (32 - bits);
        let row: Vec<String> = (0..16).map(|_| format!("{m}")).collect();
        writeln!(out, "knc_mask_b{bits}:\n\t.long {}", row.join(", ")).unwrap();
    }
}

/// The bit widths the gate measurement uses: one that spans words awkwardly
/// (11), one narrow (5), and one that never spans at all (16), so the
/// measurement separates the cost of the spanning case from the rest.
const UNPACK_WIDTHS: [u32; 3] = [5, 11, 16];

fn bitunpack() -> String {
    let mut s = header("bitunpack.S", "bitunpack.md");
    for bits in UNPACK_WIDTHS {
        unpack_kernel(&mut s, bits, Mode::Plain);
    }
    mask_constants(&mut s, &UNPACK_WIDTHS);
    writeln!(s, "\n\t.section .note.GNU-stack,\"\",@progbits").unwrap();
    s
}

/// Every width, both directions: the assembly half of `libknc`.
///
/// Not committed. At about 25000 lines it is a build product, generated by
/// `card/userland/components/libknc.sh` into the build tree the way a
/// compiler's own output is. `card/examples/bitunpack.S` stays committed
/// because it is the artifact a published measurement refers to.
fn codec() -> String {
    let widths: Vec<u32> = (1..=32).collect();
    let mut s = header("knc_codec.S", "card/lib/knc/knc.md");
    for mode in Mode::all() {
        for &bits in &widths {
            unpack_kernel(&mut s, bits, mode);
        }
    }
    for &bits in &widths {
        pack_kernel(&mut s, bits);
    }
    for mode in [Mode::For, Mode::Delta] {
        transform_kernel(&mut s, mode);
    }
    dispatch_thunks(&mut s);
    dispatch_tables(&mut s, &widths);
    mask_constants(&mut s, &widths);
    writeln!(s, "\n\t.section .note.GNU-stack,\"\",@progbits").unwrap();
    s
}

/// Positions per lane in the FastLanes layout: 1024 values over 32 lanes.
const FLS_POSITIONS: usize = 32;

/// `knc_fls_unffor_bN`: FastLanes' `unffor` for 32-bit values, on the
/// vector unit.
///
/// This is `unpack_kernel` in FastLanes' layout rather than libknc's, and
/// the difference is only in the addresses. FastLanes puts value `i` in
/// lane `i % 32` at position `i / 32` (see `unffor_11bw_32ow_32crw_1uf` in
/// the generated `fastlanes_gen_unffor.cpp`: it reads `in + w*32 + i` and
/// writes `out + p*32 + i` for `i` in 0..32), so a lane row is 32 int32,
/// which is 128 bytes, which is two vectors. libknc uses 16 lanes and one.
///
/// Lanes 0 to 15 and lanes 16 to 31 of a row take the same shifts and the
/// same mask and never interact, so this is the 16-lane kernel run twice at
/// a stride of 128 bytes, once at offset 0 and once at offset 64. Register
/// pressure is unchanged and the schedule is the same.
///
/// Two things differ beyond the addresses:
///
/// - **The base is a scalar, broadcast.** FastLanes' generated code does
///   `base_0 = *(a_base_p)` and adds that one value to all 1024, where
///   libknc's FOR mode carries a different base per lane. `vpbroadcastd`
///   does it in one instruction, once per block.
/// - **The input is not 64-byte aligned, so the loads are the unaligned
///   pair.** A FastLanes bitpacked segment starts at an arbitrary multiple
///   of four inside the file buffer; measured residues modulo 64 on a
///   three-column round trip were 8, 48 and 60 (2026-09-20). `vmovaps`
///   would fault, so every word is `vloadunpackld` plus `vloadunpackhd`.
///   The output is FastLanes' own `alignas(64)` buffer and is stored with
///   plain aligned stores.
///
/// The `ld` instructions of a group are emitted before any of its `hd`
/// instructions, because `hd` merges into the register `ld` wrote and the
/// two are dependent; separating them by the rest of the group hides that
/// the same way the shifts are separated.
///
/// The pair reads up to 60 bytes past the end of the input, because it
/// always touches the whole of both 64-byte lines around the address (ISA
/// reference 327364-001, VLOADUNPACKLD: "the memory region accessed will
/// always be between linear_address & (~0x3F) and (linear_address &
/// (~0x3F)) + 63"). That needs nothing from the caller. Those bytes are in
/// the same 64-byte line as the last byte of the input, a line never
/// crosses a page, so the read cannot reach an unmapped one; and the one
/// case where the address is itself 64-byte aligned the same section
/// exempts from #PF outright.
fn fls_unffor_kernel(out: &mut String, bits: u32) {
    let temp = |p: usize, half: usize| Zmm(WORD_REGS + (2 * p + half) as u8);
    let maskreg = Zmm(30);
    let base = Zmm(26);
    let name = format!("knc_fls_unffor_b{bits}");
    let sig = format!(
        "void {name}(const unsigned *in, unsigned *out, const unsigned *base): rdi = in ({} bytes, 4-byte aligned), rsi = out (1024 int32, 64-byte aligned), rdx = base (one int32)",
        128 * bits
    );
    function(out, &name, &sig);
    writeln!(out, "{}", vpbroadcastd(base, mem(Gpr::Rdx, 0), K(0)).gas()).unwrap();

    // A zero-bit column carries no bits at all: every value is the base.
    // FastLanes emits this case (`unffor_0bw_32ow_32crw_1uf`) and the
    // dispatch table has a real entry for it, unlike libknc's.
    if bits == 0 {
        for v in 0..FLS_POSITIONS {
            for h in 0..2 {
                let off = 128 * v as i32 + 64 * h;
                writeln!(out, "{}", vmovaps_store(mem(Gpr::Rsi, off), base).gas()).unwrap();
            }
        }
        end_function(out, &name);
        return;
    }

    if bits < 32 {
        writeln!(out, "\tleaq knc_fls_mask_b{bits}(%rip), %rax").unwrap();
        writeln!(out, "{}", vmovaps_load(maskreg, mem(Gpr::Rax, 0)).gas()).unwrap();
    }

    for half in 0..2usize {
        let word_at = |w: usize| mem(Gpr::Rdi, 128 * w as i32 + 64 * half as i32);
        let word_hi = |w: usize| mem(Gpr::Rdi, 128 * w as i32 + 64 * half as i32 + 64);
        let slot = |v: usize| mem(Gpr::Rsi, 128 * v as i32 + 64 * half as i32);

        for start in (0..FLS_POSITIONS).step_by(GROUP) {
            let group: Vec<usize> = (start..start + GROUP).collect();
            let first_word = place(bits, group[0]).0;
            let last = *group.last().unwrap();
            let last_word = (bits as usize * last + bits as usize - 1) / 32;
            let n_words = last_word - first_word + 1;

            assert!(
                n_words <= WORD_REGS as usize,
                "a group of {GROUP} values of {bits} bits needs {n_words} words"
            );
            for w in 0..n_words {
                writeln!(out, "{}", vloadunpackld(Zmm(w as u8), word_at(first_word + w), K(0)).gas()).unwrap();
            }
            for w in 0..n_words {
                writeln!(out, "{}", vloadunpackhd(Zmm(w as u8), word_hi(first_word + w), K(0)).gas()).unwrap();
            }
            let wreg = |w: usize| Zmm((w - first_word) as u8);
            let result = |p: usize, v: usize| {
                if bits == 32 {
                    wreg(place(bits, v).0)
                } else {
                    temp(p, 0)
                }
            };

            for (p, &v) in group.iter().enumerate() {
                let (w, s) = place(bits, v);
                if s != 0 {
                    writeln!(out, "{}", vpsrld(temp(p, 0), Src::Reg(wreg(w)), s, K(0)).gas()).unwrap();
                }
            }
            for (p, &v) in group.iter().enumerate() {
                let (w, s) = place(bits, v);
                if u32::from(s) + bits > 32 {
                    writeln!(out, "{}", vpslld(temp(p, 1), Src::Reg(wreg(w + 1)), 32 - s, K(0)).gas()).unwrap();
                }
            }
            for (p, &v) in group.iter().enumerate() {
                let (_, s) = place(bits, v);
                if u32::from(s) + bits > 32 {
                    writeln!(out, "{}", vpord(temp(p, 0), temp(p, 0), Src::Reg(temp(p, 1)), K(0)).gas()).unwrap();
                }
            }
            for (p, &v) in group.iter().enumerate() {
                let (w, s) = place(bits, v);
                if u32::from(s) + bits != 32 {
                    let src = if s == 0 { wreg(w) } else { temp(p, 0) };
                    writeln!(out, "{}", vpandd(temp(p, 0), src, Src::Reg(maskreg), K(0)).gas()).unwrap();
                }
            }
            for (p, &v) in group.iter().enumerate() {
                writeln!(out, "{}", vpaddd(temp(p, 1), base, Src::Reg(result(p, v)), K(0)).gas()).unwrap();
            }
            for (p, &v) in group.iter().enumerate() {
                writeln!(out, "{}", vmovaps_store(slot(v), temp(p, 1)).gas()).unwrap();
            }
        }
    }
    end_function(out, &name);
}

/// The run-time entry point the FastLanes patch calls, and its table.
///
/// The table has 33 entries and index 0 is a real kernel, not null: a
/// zero-bit column is a normal FastLanes case, where every value equals
/// the frame of reference.
fn fls_dispatch(out: &mut String, widths: &[u32]) {
    function(
        out,
        "knc_fls_unffor",
        "void knc_fls_unffor(const unsigned *in, unsigned *out, unsigned bw, const unsigned *base): FastLanes layout, 1024 values; bw above 32 returns without writing",
    );
    writeln!(out, "\tmovl %edx, %eax").unwrap();
    writeln!(out, "\tcmpl $32, %eax").unwrap();
    writeln!(out, "\tja 1f").unwrap();
    writeln!(out, "\tmovq %rcx, %rdx").unwrap();
    writeln!(out, "\tleaq knc_fls_unffor_table(%rip), %r9").unwrap();
    writeln!(out, "\tjmp *(%r9,%rax,8)").unwrap();
    writeln!(out, "1:").unwrap();
    end_function(out, "knc_fls_unffor");

    writeln!(out, "\n\t.section .rodata\n\t.balign 8").unwrap();
    writeln!(out, "\t.globl knc_fls_unffor_table\n\t.type knc_fls_unffor_table, @object").unwrap();
    writeln!(out, "knc_fls_unffor_table:").unwrap();
    for bits in widths {
        writeln!(out, "\t.quad knc_fls_unffor_b{bits}").unwrap();
    }
    writeln!(out, "\t.size knc_fls_unffor_table, .-knc_fls_unffor_table").unwrap();
}

/// The lane masks, named apart from libknc's so that the FastLanes object
/// links on its own.
fn fls_mask_constants(out: &mut String, widths: &[u32]) {
    writeln!(out, "\n\t.section .rodata\n\t.balign 64").unwrap();
    for &bits in widths {
        if bits == 0 || bits == 32 {
            continue;
        }
        let m = 0xFFFF_FFFFu32 >> (32 - bits);
        let row: Vec<String> = (0..16).map(|_| format!("{m}")).collect();
        writeln!(out, "knc_fls_mask_b{bits}:\n\t.long {}", row.join(", ")).unwrap();
    }
}

/// Every width of FastLanes' 32-bit `unffor`: the assembly half of the
/// FastLanes backend.
///
/// Only 32-bit values are here, and that is a hardware limit rather than a
/// choice. FastLanes instantiates `unffor` for 64, 32, 16 and 8 bit
/// values; Knights Corner has no byte or word integer vector instruction
/// at all, and its 64-bit integer set is exactly `vfixupnanpd`, `vpandnq`,
/// `vpandq`, `vpblendmq`, `vporq` and `vpxorq` (ISA reference
/// 327364-001, appendix D.1.8), with no add and no shift. Three of the
/// four widths stay on FastLanes' scalar code.
fn fastlanes() -> String {
    let widths: Vec<u32> = (0..=32).collect();
    let mut s = header("knc_fls.S", "card/lib/knc-fls/knc-fls.md");
    for &bits in &widths {
        fls_unffor_kernel(&mut s, bits);
    }
    fls_dispatch(&mut s, &widths);
    fls_mask_constants(&mut s, &widths);
    writeln!(s, "\n\t.section .note.GNU-stack,\"\",@progbits").unwrap();
    s
}
/// `vpu_int_probe`: one new integer instruction per output slot, so a
/// wrong encoding localises to a single instruction rather than to a
/// kernel.
///
/// The encodings in lib.rs for the float64 set are pinned to Intel's k1om
/// kernel macros; the integer set has no such reference, only the opcode
/// table in the ISA document. A wrong prefix bit does not usually fault,
/// it decodes as some other valid instruction and returns plausible
/// numbers, so the check has to be semantic: set known inputs, run exactly
/// one instruction, compare against the scalar result in C (vpu_int.md).
///
/// The cases are chosen to cover the fields that are least cross-checkable:
/// a memory second source (SSS as the up-conversion field, 000), the `NDD`
/// immediate shifts (destination in `vvvv`, opcode extension in ModRM.reg),
/// a destination above zmm15 (the `V'` bit), and merge masking.
fn int_probe() -> String {
    let mut s = header("vpu_int.S", "vpu_int.md");
    function(
        &mut s,
        "vpu_int_probe",
        "void vpu_int_probe(const int *in, int *out): rdi = in (16 int32 a at 0, 16 int32 b at 64, both 64-byte aligned), rsi = out (16 slots of 16 int32)",
    );
    // zmm0 = a, zmm1 = b, zmm2 = result, zmm17 = the high-register case.
    for l in [vmovaps_load(Zmm(0), mem(Gpr::Rdi, 0)), vmovaps_load(Zmm(1), mem(Gpr::Rdi, 64))] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    let slot = |n: i32| mem(Gpr::Rsi, 64 * n);
    let cases: [(i32, Insn); 14] = [
        (0, vpaddd(Zmm(2), Zmm(0), z(1), K(0))),
        (1, vpsubd(Zmm(2), Zmm(0), z(1), K(0))),
        (2, vpandd(Zmm(2), Zmm(0), z(1), K(0))),
        (3, vpandnd(Zmm(2), Zmm(0), z(1), K(0))),
        (4, vpord(Zmm(2), Zmm(0), z(1), K(0))),
        (5, vpxord(Zmm(2), Zmm(0), z(1), K(0))),
        (6, vpslld(Zmm(2), z(0), 1, K(0))),
        (7, vpslld(Zmm(2), z(0), 11, K(0))),
        (8, vpsrld(Zmm(2), z(0), 11, K(0))),
        (9, vpsrad(Zmm(2), z(0), 11, K(0))),
        (10, vpsrad(Zmm(2), z(0), 31, K(0))),
        // The same shift as slot 7, with the source read from memory: if
        // slots 7 and 11 differ, the memory form of the NDD encoding is wrong.
        (11, vpslld(Zmm(2), at(Gpr::Rdi, 0), 11, K(0))),
        (12, vpsllvd(Zmm(2), Zmm(0), z(1), K(0))),
        // Variable shift with the count vector in memory.
        (13, vpsrlvd(Zmm(2), Zmm(0), at(Gpr::Rdi, 64), K(0))),
    ];
    for (n, insn) in &cases {
        writeln!(s, "{}", insn.gas()).unwrap();
        writeln!(s, "{}", vmovaps_store(slot(*n), Zmm(2)).gas()).unwrap();
    }
    // Merge masking: lanes whose mask bit is clear keep what the destination
    // already held. KNC has no zeroing mask, so this is the only behaviour.
    writeln!(s, "\tmovl $255, %eax").unwrap();
    writeln!(s, "{}", kmov_k_r32(K(1), Gpr::Rax).gas()).unwrap();
    for l in [
        vmovaps_load(Zmm(2), mem(Gpr::Rdi, 0)),
        vpaddd(Zmm(2), Zmm(0), z(1), K(1)),
        vmovaps_store(slot(14), Zmm(2)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    // Destination above zmm15 (V' clear) in the NDD form, under a mask.
    writeln!(s, "\tmovl $3855, %eax").unwrap(); // 0x0f0f
    writeln!(s, "{}", kmov_k_r32(K(2), Gpr::Rax).gas()).unwrap();
    for l in [
        vmovaps_load(Zmm(17), mem(Gpr::Rdi, 0)),
        vpslld(Zmm(17), z(1), 3, K(2)),
        vmovaps_store(slot(15), Zmm(17)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    // Splat one 32-bit element from memory. The source of vpbroadcastd is
    // always memory, so lane b[1] of the second input block goes to every
    // lane of slot 16.
    for l in [vpbroadcastd(Zmm(3), mem(Gpr::Rdi, 64 + 4), K(0)), vmovaps_store(slot(16), Zmm(3))] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    // The unaligned load pair on an address that happens to be aligned:
    // the high half then transfers nothing and the low half alone is the
    // whole vector. Slot 17 must equal the first input block.
    for l in [
        vloadunpackld(Zmm(3), mem(Gpr::Rdi, 0), K(0)),
        vloadunpackhd(Zmm(3), mem(Gpr::Rdi, 64), K(0)),
        vmovaps_store(slot(17), Zmm(3)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    end_function(&mut s, "vpu_int_probe");

    // The same pair on an address that is only element-aligned, which is
    // what FastLanes hands the unpack kernels: its bitpacked segments start
    // at an arbitrary multiple of four inside the file buffer (measured
    // 2026-09-20, residues 8, 48 and 60 on a three-column round trip).
    function(
        &mut s,
        "vpu_int_unaligned",
        "void vpu_int_unaligned(const int *un, int *out): rdi = un (any multiple of 4), rsi = out (64-byte aligned, 16 int32)",
    );
    for l in [
        vloadunpackld(Zmm(0), mem(Gpr::Rdi, 0), K(0)),
        vloadunpackhd(Zmm(0), mem(Gpr::Rdi, 64), K(0)),
        vmovaps_store(mem(Gpr::Rsi, 0), Zmm(0)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    end_function(&mut s, "vpu_int_unaligned");
    writeln!(s, "\n\t.section .note.GNU-stack,\"\",@progbits").unwrap();
    s
}

fn probe() -> String {
    let mut s = header("vpu_probe.S", "vpu_probe.md");
    function(
        &mut s,
        "vpu_probe",
        "void vpu_probe(const double *in, double *out, unsigned *mask): rdi = in (a at 0, b at 64), rsi = out, rdx = mask",
    );
    let lines = [
        vmovapd_load(Zmm(0), at(Gpr::Rdi, 0), K(0)),
        vmovapd_load(Zmm(1), at(Gpr::Rdi, 64), K(0)),
        vaddpd(Zmm(2), Zmm(0), z(1), K(0)),
        vmovapd_store(mem(Gpr::Rsi, 0), Zmm(2), K(0)),
        vmulpd(Zmm(3), Zmm(0), z(1), K(0)),
        vmovapd_store(mem(Gpr::Rsi, 64), Zmm(3), K(0)),
        vmovapd_load(Zmm(4), z(0), K(0)),
        vfmadd213pd(Zmm(4), Zmm(1), z(0), K(0)),
        vmovapd_store(mem(Gpr::Rsi, 128), Zmm(4), K(0)),
        vsubpd(Zmm(5), Zmm(0), z(1), K(0)),
        vmovapd_store(mem(Gpr::Rsi, 192), Zmm(5), K(0)),
        vmovapd_load(Zmm(31), z(2), K(0)),
        vmovapd_store(mem(Gpr::Rsi, 256), Zmm(31), K(0)),
    ];
    for l in &lines {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    writeln!(s, "\tmovl $15, %eax").unwrap();
    writeln!(s, "{}", kmov_k_r32(K(3), Gpr::Rax).gas()).unwrap();
    for l in [
        vmovapd_load(Zmm(6), z(1), K(0)),
        vaddpd(Zmm(6), Zmm(0), z(0), K(3)),
        vmovapd_store(mem(Gpr::Rsi, 320), Zmm(6), K(0)),
        vcmppd(K(2), Zmm(0), z(1), Cmp::Lt, K(0)),
        kmov_r32_k(Gpr::Rax, K(2)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    writeln!(s, "\tmovl %eax, (%rdx)").unwrap();
    end_function(&mut s, "vpu_probe");

    function(
        &mut s,
        "vpu_set",
        "void vpu_set(const void *area): rdi = 64-byte aligned area, 32 x 64 bytes of zmm then 8 x u16 masks at 2048",
    );
    set_body(&mut s);
    end_function(&mut s, "vpu_set");
    function(&mut s, "vpu_get", "void vpu_get(void *area): the same layout, stored");
    get_body(&mut s);
    end_function(&mut s, "vpu_get");
    writeln!(s, "\n\t.section .note.GNU-stack,\"\",@progbits").unwrap();
    s
}

fn mandel() -> String {
    let mut s = header("mandel_vpu.S", "mandel_vpu.md");
    function(&mut s, "mandel8_vpu", "void mandel8_vpu(const double *c, double *out, int maxiter): rdi = c (cr at 0, ci at 64), rsi = out (iteration counts at 0, |z|^2 at 64), edx = maxiter");
    writeln!(s, "\tleaq mandel8_consts(%rip), %rcx").unwrap();
    // Registers: 0 cr, 1 ci, 2 zr, 3 zi, 4 zr2, 5 zi2, 6 n, 7 two, 8 four, 9 one, 10 |z|^2, 11 2*zr.
    for l in [
        vmovapd_load(Zmm(0), at(Gpr::Rdi, 0), K(0)),
        vmovapd_load(Zmm(1), at(Gpr::Rdi, 64), K(0)),
        vmovapd_load(Zmm(2), at(Gpr::Rcx, 192), K(0)),
        vmovapd_load(Zmm(3), at(Gpr::Rcx, 192), K(0)),
        vmovapd_load(Zmm(4), at(Gpr::Rcx, 192), K(0)),
        vmovapd_load(Zmm(5), at(Gpr::Rcx, 192), K(0)),
        vmovapd_load(Zmm(6), at(Gpr::Rcx, 192), K(0)),
        vmovapd_load(Zmm(7), at(Gpr::Rcx, 0), K(0)),
        vmovapd_load(Zmm(8), at(Gpr::Rcx, 64), K(0)),
        vmovapd_load(Zmm(9), at(Gpr::Rcx, 128), K(0)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    writeln!(s, "\tmovl $255, %eax").unwrap();
    writeln!(s, "{}", kmov_k_r32(K(1), Gpr::Rax).gas()).unwrap();
    writeln!(s, "\txorl %r8d, %r8d").unwrap();
    writeln!(s, "1:").unwrap();
    // k1 &= (zr2 + zi2 < 4); stop when no lane is active.
    for l in [
        vaddpd(Zmm(10), Zmm(4), z(5), K(0)),
        vcmppd(K(1), Zmm(10), z(8), Cmp::Lt, K(1)),
        kortest(K(1), K(1)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    writeln!(s, "\tjz 2f").unwrap();
    // Active lanes: zi = 2*zr*zi + ci; zr = zr2 - zi2 + cr; zr2 = zr*zr; zi2 = zi*zi; n += 1.
    for l in [
        vmulpd(Zmm(11), Zmm(2), z(7), K(1)),
        vfmadd213pd(Zmm(3), Zmm(11), z(1), K(1)),
        vsubpd(Zmm(2), Zmm(4), z(5), K(1)),
        vaddpd(Zmm(2), Zmm(2), z(0), K(1)),
        vmulpd(Zmm(4), Zmm(2), z(2), K(1)),
        vmulpd(Zmm(5), Zmm(3), z(3), K(1)),
        vaddpd(Zmm(6), Zmm(6), z(9), K(1)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    writeln!(s, "\tincl %r8d\n\tcmpl %edx, %r8d\n\tjl 1b").unwrap();
    writeln!(s, "2:").unwrap();
    for l in [
        vmovapd_store(mem(Gpr::Rsi, 0), Zmm(6), K(0)),
        vaddpd(Zmm(10), Zmm(4), z(5), K(0)),
        vmovapd_store(mem(Gpr::Rsi, 64), Zmm(10), K(0)),
    ] {
        writeln!(s, "{}", l.gas()).unwrap();
    }
    end_function(&mut s, "mandel8_vpu");
    writeln!(s, "\n\t.section .rodata\n\t.balign 64\nmandel8_consts:").unwrap();
    for v in ["2.0", "4.0", "1.0", "0.0"] {
        let row: Vec<&str> = vec![v; 8];
        writeln!(s, "\t.double {}", row.join(", ")).unwrap();
    }
    writeln!(s, "\n\t.section .note.GNU-stack,\"\",@progbits").unwrap();
    s
}

fn kernel_header() -> String {
    let mut s = String::new();
    s.push_str("/* SPDX-License-Identifier: GPL-2.0 */\n");
    s.push_str("/*\n * Knights Corner vector unit state: 32 zmm registers of 64 bytes and 8\n");
    s.push_str(" * mask registers of 16 bits, kept after the FXSAVE image in the task's\n");
    s.push_str(" * fpstate. FXSAVE does not store the zmm registers and FXRSTOR clears\n");
    s.push_str(" * bits 0:127 of every one of them (ISA reference 327364-001, B.5 and\n");
    s.push_str(" * B.4), so the restore has to run after fxrstor.\n *\n");
    s.push_str(" * Generated by knc-mvex-gen kernel-header (host/crates/knc-mvex in the\n");
    s.push_str(" * project tree), whose tests pin the encodings to Intel's k1om kernel\n");
    s.push_str(" * macros. Vector instructions are byte sequences because the assembler\n");
    s.push_str(" * does not know the MVEX prefix.\n */\n");
    s.push_str("#ifndef _ASM_X86_KNC_VPU_H\n#define _ASM_X86_KNC_VPU_H\n\n");
    s.push_str("#define KNC_VPU_STATE_OFFSET\t512\t/* right after the FXSAVE image */\n");
    s.push_str("#define KNC_VPU_K_OFFSET\t2048\t/* the mask registers, after the zmm registers */\n");
    s.push_str("#define KNC_VPU_STATE_SIZE\t2112\t/* zmm and masks, rounded up to 64 bytes */\n");
    s.push_str("#define KNC_FPSTATE_SIZE\t(KNC_VPU_STATE_OFFSET + KNC_VPU_STATE_SIZE)\n\n");
    s.push_str("#ifndef __ASSEMBLY__\n\n");
    s.push_str("/* Store zmm0..31 and k0..k7 into a 64-byte aligned area of KNC_VPU_STATE_SIZE bytes. */\n");
    s.push_str("static inline void knc_vpu_save(void *area)\n{\n\tasm volatile(\n");
    for r in 0..32u8 {
        writeln!(s, "\t\t{}", vmovaps_store(mem(Gpr::Rax, 64 * i32::from(r)), Zmm(r)).c_string()).unwrap();
    }
    for k in 0..8u8 {
        writeln!(s, "\t\t{}", kmov_r32_k(Gpr::Rcx, K(k)).c_string()).unwrap();
        writeln!(s, "\t\t\"movw %%cx, {}(%%rax)\\n\\t\"", 2048 + 2 * i32::from(k)).unwrap();
    }
    s.push_str("\t\t: : \"a\" (area) : \"rcx\", \"memory\");\n}\n\n");
    s.push_str("/* Load them back; call after fxrstor, which zeroes the low 128 bits of each zmm. */\n");
    s.push_str("static inline void knc_vpu_restore(const void *area)\n{\n\tasm volatile(\n");
    for r in 0..32u8 {
        writeln!(s, "\t\t{}", vmovaps_load(Zmm(r), mem(Gpr::Rax, 64 * i32::from(r))).c_string()).unwrap();
    }
    for k in 0..8u8 {
        writeln!(s, "\t\t\"movzwl {}(%%rax), %%ecx\\n\\t\"", 2048 + 2 * i32::from(k)).unwrap();
        writeln!(s, "\t\t{}", kmov_k_r32(K(k), Gpr::Rcx).c_string()).unwrap();
    }
    s.push_str("\t\t: : \"a\" (area) : \"rcx\", \"memory\");\n}\n\n");
    s.push_str("#endif /* __ASSEMBLY__ */\n#endif /* _ASM_X86_KNC_VPU_H */\n");
    s
}

fn main() {
    let what = env::args().nth(1).unwrap_or_default();
    let text = match what.as_str() {
        "probe" => probe(),
        "int-probe" => int_probe(),
        "bitunpack" => bitunpack(),
        "codec" => codec(),
        "fastlanes" => fastlanes(),
        "memcpy" => memcpy_kernel(),
        "mandel" => mandel(),
        "kernel-header" => kernel_header(),
        _ => {
            eprintln!("usage: knc-mvex-gen probe|int-probe|bitunpack|codec|fastlanes|mandel|memcpy|kernel-header");
            std::process::exit(2);
        }
    };
    print!("{text}");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed files are this generator's output. An encoder change
    /// fails here until the files are regenerated (main.md), so the card
    /// never runs bytes the tests in lib.rs did not see.
    #[test]
    fn committed_assembly_is_current() {
        assert_eq!(probe(), include_str!("../../../../card/examples/vpu_probe.S"));
        assert_eq!(int_probe(), include_str!("../../../../card/examples/vpu_int.S"));
        assert_eq!(mandel(), include_str!("../../../../card/examples/mandel_vpu.S"));
        assert_eq!(memcpy_kernel(), include_str!("../../../../card/examples/vpu_memcpy.S"));
    }

    /// The kernel header as patch 0024 adds it: the `+` lines of its
    /// `knc_vpu.h` hunk, less the marker.
    #[test]
    fn kernel_header_matches_patch_0024() {
        let patch = include_str!("../../../../card/kernel/patches/0024-x86-knc-save-and-restore-the-vector-unit-state-on-co.patch");
        let hunk = patch
            .split("+++ b/arch/x86/include/asm/knc_vpu.h\n")
            .nth(1)
            .expect("the patch adds the header");
        let header: String = hunk
            .lines()
            .take_while(|l| !l.starts_with("diff --git"))
            .filter_map(|l| l.strip_prefix('+'))
            .map(|l| format!("{l}\n"))
            .collect();
        assert_eq!(kernel_header(), header);
    }
}
