#!/usr/bin/env bash
# phi-autoboot.sh: run the card automatically from a systemd user service.
# No root: the unit runs phictl boot in the user's systemd instance with the
# same arguments as phi-up.sh (control socket, SSH forwarder on
# 127.0.0.1:2222, the persistent disk, host RAM as swap). Usage:
#   scripts/phi-autoboot.sh install [DISK [HOSTMEM]]   # write, enable and start phi.service
#     HOSTMEM, e.g. 6G, gives the card that much host RAM (swap and /dev/phihost); also $PHI_HOST_MEM
#   scripts/phi-autoboot.sh at-boot          # start at host boot, with nobody logged in (linger)
#   scripts/phi-autoboot.sh at-login         # back to starting at the first login
#   scripts/phi-autoboot.sh remove           # disable and remove it
#   scripts/phi-autoboot.sh status
# See phi-autoboot.md.
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/.." && pwd)
unit_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
unit="$unit_dir/phi.service"
me=$(id -un)
linger() { loginctl show-user "$me" -p Linger --value 2>/dev/null || echo unknown; }
cmd="${1:-status}"
case "$cmd" in
    install)
        disk="${2:-${PHI_DISK:-}}"
        hostmem="${3:-${PHI_HOST_MEM:-}}"
        P="$root/host/target/debug/phictl"
        wait="$root/scripts/phi-wait-vfio.sh"
        kernel="$root/card/kernel/build/out/arch/x86/boot/bzImage"
        initrd="$root/card/initramfs/build/initramfs.cpio.gz"
        [ -x "$P" ] && [ -s "$kernel" ] && [ -s "$initrd" ] || { echo "$0: build the host tools, kernel and initramfs first" >&2; exit 1; }
        id -nG | tr ' ' '\n' | grep -qx phi || { echo "$0: not in group phi (sudo scripts/setup-arch.sh, then log in again)" >&2; exit 1; }
        diskarg=""
        if [ -n "$disk" ]; then
            [ -f "$disk" ] || { echo "$0: disk image $disk not found (scripts/phi-disk.sh create PATH SIZE)" >&2; exit 1; }
            diskarg=" --disk \"$disk\""
        fi
        [ -n "$hostmem" ] && diskarg="$diskarg --host-mem $hostmem"
        mkdir -p "$unit_dir"
        cat > "$unit" <<UNIT
# Generated by scripts/phi-autoboot.sh (Intel Phi 3120A project); edit the
# script, not this file. Runs the Xeon Phi from the user's systemd instance:
# at the first login by default, or at host boot with nobody logged in when
# lingering is on (scripts/phi-autoboot.sh at-boot).
[Unit]
Description=Intel Xeon Phi 3120A: boot the card and serve it (phictl)
[Service]
Type=simple
# Console output; the control socket lives in \$XDG_RUNTIME_DIR/phictl.
Environment=PHICTL_SOCKET=%t/phictl/control.sock
ExecStartPre=/usr/bin/mkdir -p -m 700 %t/phictl
# With lingering this unit can start before systemd-modules-load has inserted
# vfio_pci and before udev has applied the group-phi ownership. Wait for the
# end state rather than trying to order against either. A ConditionPathExists
# would mark the unit *skipped* instead of failed, and Restart= never acts on
# a skip; this exits non-zero, which Restart=on-failure does act on.
ExecStartPre="$wait" 60
ExecStart="$P" boot --kernel "$kernel" --initrd "$initrd" --cmdline "earlyprintk=phiring console=ttyPHI0" --serve %t/phictl/control.sock --forward 2222:22$diskarg
# Stop: a plain poweroff, which signals the card's PID 1 so init stops the
# services, releases swap and unmounts /data; then end phictl, which releases
# VFIO and resets the card. Waiting for the agent to stop answering is how we
# know init got that far.
ExecStop=/bin/sh -c 'PHICTL_SOCKET=%t/phictl/control.sock; export PHICTL_SOCKET; timeout 5 "$P" exec -- sh -c "poweroff >/dev/null 2>&1 &" >/dev/null 2>&1; for _ in 1 2 3 4 5 6 7 8; do timeout 2 "$P" status >/dev/null 2>&1 || break; sleep 1; done'
KillSignal=SIGINT
TimeoutStopSec=20
Restart=on-failure
RestartSec=10
[Install]
WantedBy=default.target
UNIT
        systemctl --user daemon-reload
        systemctl --user enable --now phi.service
        echo "$0: phi.service installed at $unit and started; check with: phi status"
        if [ "$(linger)" = yes ]; then
            echo "$0: lingering is on, so it starts at host boot and runs with nobody logged in"
        else
            echo "$0: it starts at the first login and stops with the last session"
            echo "$0: for host boot instead: $0 at-boot"
        fi
        ;;

    at-boot)
        # Lingering makes systemd-logind start this user's manager at host
        # boot and keep it after the last logout, which is what turns a user
        # unit into a boot service without giving it root. It is per USER,
        # not per unit: every enabled user unit starts at boot too.
        loginctl enable-linger "$me"
        [ -f "$unit" ] && systemctl --user enable phi.service > /dev/null 2>&1 || true
        echo "$0: lingering on for $me."
        echo "$0: phi.service now starts at host boot, runs with nobody logged in,"
        echo "$0: and survives logout. The card is still reachable only from this"
        echo "$0: host: the socket is mode 0600 owned by $me, the SSH forwarder"
        echo "$0: binds 127.0.0.1 only."
        echo "$0: lingering is per user, so these start at boot as well:"
        systemctl --user list-unit-files --state=enabled --no-pager 2>/dev/null |
            awk 'NR>1 && $1 ~ /\.(service|socket|timer|target|path)$/ {print "    " $1}'
        ;;

    at-login)
        loginctl disable-linger "$me"
        echo "$0: lingering off for $me: phi.service starts at the first login"
        echo "$0: and the card is released when the last session ends."
        ;;

    remove)
        systemctl --user disable --now phi.service 2>/dev/null || true
        rm -f "$unit"
        systemctl --user daemon-reload
        echo "$0: phi.service removed (lingering, if on, is left alone: $0 at-login)"
        ;;

    status)
        if [ "$(linger)" = yes ]; then
            printf 'linger    yes (phi.service starts at host boot, runs with nobody logged in)\n'
        else
            printf 'linger    %s (phi.service starts at the first login)\n' "$(linger)"
        fi
        systemctl --user status phi.service --no-pager 2>&1 | head -12 || true
        ;;

    *)
        echo "usage: $0 install [DISK [HOSTMEM]] | at-boot | at-login | remove | status" >&2
        exit 2
        ;;
esac
