#!/usr/bin/env bash
# phi-autoboot.sh: boot the card automatically at login with a systemd user
# service, and keep it up while a session exists. No root: the unit runs
# phictl boot in the user's systemd instance with the same arguments as
# phi-up.sh (control socket, SSH forwarder on 127.0.0.1:2222, the persistent
# disk). Usage:
#   scripts/phi-autoboot.sh install [DISK [HOSTMEM]]   # write, enable and start phi.service
#     HOSTMEM, e.g. 4G, gives the card that much host RAM (swap and /dev/phihost); also $PHI_HOST_MEM
#   scripts/phi-autoboot.sh remove           # disable and remove it
#   scripts/phi-autoboot.sh status
# See phi-autoboot.md.
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/.." && pwd)
unit_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
unit="$unit_dir/phi.service"
cmd="${1:-status}"
case "$cmd" in
    install)
        disk="${2:-${PHI_DISK:-}}"
        hostmem="${3:-${PHI_HOST_MEM:-}}"
        P="$root/host/target/debug/phictl"
        kernel="$root/card/kernel/build/out/arch/x86/boot/bzImage"
        initrd="$root/card/initramfs/build/initramfs.cpio.gz"
        [ -x "$P" ] && [ -s "$kernel" ] && [ -s "$initrd" ] || { echo "$0: build the host tools, kernel and initramfs first" >&2; exit 1; }
        id -nG | tr ' ' '\n' | grep -qx phi || { echo "$0: not in group phi (sudo scripts/setup-arch.sh, then log in again)" >&2; exit 1; }
        diskarg=""
        if [ -n "$disk" ]; then
            [ -f "$disk" ] || { echo "$0: disk image $disk not found (scripts/phi-disk.sh create PATH SIZE)" >&2; exit 1; }
            diskarg=" --disk \"$disk\""
        fi
        [ -n "$hostmem" ] && diskarg="$diskarg --host-mem $hostmem"
        mkdir -p "$unit_dir"
        cat > "$unit" <<UNIT
# Generated by scripts/phi-autoboot.sh (Intel Phi 3120A project); edit the
# script, not this file. Boots the Xeon Phi when the user session starts.
[Unit]
Description=Intel Xeon Phi 3120A: boot the card and serve it (phictl)
# The VFIO device node belongs to group phi and appears at host boot.
ConditionPathExists=/dev/vfio/vfio
[Service]
Type=simple
# Console output; the control socket lives in \$XDG_RUNTIME_DIR/phictl.
Environment=PHICTL_SOCKET=%t/phictl/control.sock
ExecStartPre=/usr/bin/mkdir -p -m 700 %t/phictl
ExecStart="$P" boot --kernel "$kernel" --initrd "$initrd" --cmdline "earlyprintk=phiring console=ttyPHI0" --serve %t/phictl/control.sock --forward 2222:22$diskarg
# Stop: a plain poweroff, which signals the card's PID 1 so init stops the
# services, releases swap and unmounts /data; then end phictl, which releases
# VFIO and resets the card. Waiting for the agent to stop answering is how we
# know init got that far.
ExecStop=/bin/sh -c 'PHICTL_SOCKET=%t/phictl/control.sock; export PHICTL_SOCKET; timeout 5 "$P" exec -- sh -c "poweroff >/dev/null 2>&1 &" >/dev/null 2>&1; for _ in 1 2 3 4 5 6 7 8; do timeout 2 "$P" status >/dev/null 2>&1 || break; sleep 1; done'
KillSignal=SIGINT
TimeoutStopSec=20
Restart=on-failure
RestartSec=10
[Install]
WantedBy=default.target
UNIT
        systemctl --user daemon-reload
        systemctl --user enable --now phi.service
        echo "$0: phi.service installed at $unit and started; check with: systemctl --user status phi.service"
        echo "$0: it starts at every login (default.target) and stops with the last session"
        ;;
    remove)
        systemctl --user disable --now phi.service 2>/dev/null || true
        rm -f "$unit"
        systemctl --user daemon-reload
        echo "$0: phi.service removed"
        ;;
    status)
        systemctl --user status phi.service --no-pager 2>&1 | head -12 || true
        ;;
    *)
        echo "usage: $0 install [DISK] | remove | status" >&2
        exit 2
        ;;
esac
