/*
 * vpu_probe.c: does the card's vector unit execute from user space, and do
 * the encodings in vpu_probe.S (generated by knc-mvex-gen) do what they
 * say? Runs float64 add, multiply, fused multiply-add, subtract, a move
 * through zmm31, a masked add and a compare into a mask register, and
 * checks every lane against scalar arithmetic. Compiled on the card:
 *   cc -O2 -o vpu_probe vpu_probe.c vpu_probe.S
 * See vpu_probe.md.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* vpu_probe.S: in[0..7] = a, in[8..15] = b; out gets 6 vectors; *mask = (a < b) lanes. */
void vpu_probe(const double *in, double *out, unsigned *mask);

static int check(const char *what, const double *got, const double *want)
{
	for (int i = 0; i < 8; i++)
		if (got[i] != want[i]) {
			printf("FAIL %s lane %d: got %.17g want %.17g\n", what, i, got[i], want[i]);
			return 1;
		}
	printf("ok   %s\n", what);
	return 0;
}

int main(void)
{
	double *in = aligned_alloc(64, 2 * 64);
	double *out = aligned_alloc(64, 6 * 64);
	double want[8];
	unsigned mask = 0xdead;
	int bad = 0;

	memset(out, 0, 6 * 64);
	for (int i = 0; i < 8; i++) {
		in[i] = i + 1.5;
		in[8 + i] = 2 * i - 3.25;
	}
	vpu_probe(in, out, &mask);

	for (int i = 0; i < 8; i++)
		want[i] = in[i] + in[8 + i];
	bad |= check("vaddpd", out, want);
	for (int i = 0; i < 8; i++)
		want[i] = in[i] * in[8 + i];
	bad |= check("vmulpd", out + 8, want);
	for (int i = 0; i < 8; i++)
		want[i] = in[8 + i] * in[i] + in[i];
	bad |= check("vfmadd213pd (b*a + a)", out + 16, want);
	for (int i = 0; i < 8; i++)
		want[i] = in[i] - in[8 + i];
	bad |= check("vsubpd", out + 24, want);
	for (int i = 0; i < 8; i++)
		want[i] = in[i] + in[8 + i];
	bad |= check("vmovapd through zmm31", out + 32, want);
	for (int i = 0; i < 8; i++)
		want[i] = i < 4 ? in[i] + in[i] : in[8 + i];
	bad |= check("vaddpd {k3} (lanes 0-3 only)", out + 40, want);
	unsigned wmask = 0;
	for (int i = 0; i < 8; i++)
		if (in[i] < in[8 + i])
			wmask |= 1u << i;
	if (mask != wmask) {
		printf("FAIL vcmppd/kmov: got 0x%x want 0x%x\n", mask, wmask);
		bad = 1;
	} else {
		printf("ok   vcmppd lt + kmov (mask 0x%x)\n", mask);
	}
	printf("%s\n", bad ? "VPU PROBE FAILED" : "VPU PROBE PASSED");
	return bad;
}
